name: former
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_bloc: ^8.1.5
  flutter_form_bloc: ^0.31.0
  dartx: ^1.2.0
  intl: ^0.18.1
  dorm_annotations:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_annotations
      ref: develop
  dorm_framework:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_framework
      ref: develop
  dorm_bloc_database:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_bloc_database
      ref: develop
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  dorm_generator:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_generator
      ref: develop

flutter:
  uses-material-design: true

dependency_overrides:
  meta: 1.11.0
  uuid: 3.0.4
  dorm_annotations:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_annotations
      ref: develop
  dorm_framework:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_framework
      ref: develop
  dorm_bloc_database:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_bloc_database
      ref: develop
  dorm_generator:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_generator
      ref: develop